# Лабораторная работа №2 по предмету "Теория кодирования".
Выполнили студенты группы 6404-010302D,
Журавская Елизавета и Кандалов Иван.



In [ ]:
import numpy as np

# 2.1. Сформировать порождающую матрицу линейного кода (n=7, k=4, d=3).

In [ ]:
def generate_code_matrix():
    # Определяем единичную матрицу I4 (размер 4x4)
    I4 = np.eye(4, dtype=int)

    X = np.array([[1, 1, 0],
                  [1, 0, 1],
                  [0, 1, 1],
                  [1, 1, 1]])

    # Формируем порождающую матрицу G
    G = np.hstack((I4, X)) #присоединяет данные по горизонтальной оси

    return G

G = generate_code_matrix()
print("Порождающая матрица G:\n", G)

Порождающая матрица G:
 [[1 0 0 0 1 1 0]
 [0 1 0 0 1 0 1]
 [0 0 1 0 0 1 1]
 [0 0 0 1 1 1 1]]


# 2.2 Сформировать проверочную матрицу на основе порождающей.

In [ ]:
def generate_code_matrix():
    # Определяем единичную матрицу I3 (размер 3x3)
    I3 = np.eye(3, dtype=int)

    X = np.array([[1, 1, 0],
                  [1, 0, 1],
                  [0, 1, 1],
                  [1, 1, 1]])

    # Формируем порождающую матрицу G
    H = np.vstack((I3, X)) #присоединяет данные по вертикальной оси

    return H

H = generate_code_matrix()
print("Проверочная матрица H:\n", H)

Проверочная матрица H:
 [[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 1 0]
 [1 0 1]
 [0 1 1]
 [1 1 1]]


# 2.3 Сформировать таблицу синдромов для всех однократных ошибок.

In [ ]:
n = 7
error_table = {}
for i in range(n):
    error = np.zeros(n)
    error[i] = 1
    syndrome = np.dot(error, H) % 2
    error_table[tuple(map(int, tuple(syndrome)))] = tuple(map(int, tuple(error)))


print("Таблица синдромов однократных ошибок")
for syndrome, error in error_table.items():
    print(f"Синдром {syndrome}: Ошибка {error}")

Таблица синдромов однократных ошибок
Синдром (1, 0, 0): Ошибка (1, 0, 0, 0, 0, 0, 0)
Синдром (0, 1, 0): Ошибка (0, 1, 0, 0, 0, 0, 0)
Синдром (0, 0, 1): Ошибка (0, 0, 1, 0, 0, 0, 0)
Синдром (1, 1, 0): Ошибка (0, 0, 0, 1, 0, 0, 0)
Синдром (1, 0, 1): Ошибка (0, 0, 0, 0, 1, 0, 0)
Синдром (0, 1, 1): Ошибка (0, 0, 0, 0, 0, 1, 0)
Синдром (1, 1, 1): Ошибка (0, 0, 0, 0, 0, 0, 1)


# 2.4. Сформировать кодовое слово длины n из слова длины k. Внести однократную ошибку в сформированное слово. Вычислить синдром, исправить ошибку с использованием таблицы синдромов. Убедиться в правильности полученного слова.

In [ ]:
# Кодирование сообщения
def encode_message(message, G_matrix):
    return np.dot(message, G_matrix) % 2

# Добавление однократной ошибки
def add_single_error(codeword, error_position):
    codeword_with_error = codeword.copy()
    codeword_with_error[error_position] ^= 1
    return codeword_with_error

def decode_and_correct(codeword_with_error, H_matrix, syndrome_table, syndrome_tuple):
    # Если синдром найден в таблице, исправляем ошибку
    if syndrome_tuple in syndrome_table:
        error_vector = syndrome_table[syndrome_tuple]
        # Исправляем кодовое слово, добавляя вектор ошибки
        corrected_codeword = (codeword_with_error + error_vector) % 2
        return corrected_codeword
    else:
        print("Синдром не найден в таблице.")
        return codeword_with_error


k = 4
n = 10

# Сообщение для кодирования (слово длины k)
message = np.array([1, 0, 1, 1])
print("\nИсходное сообщение:", message)
codeword = encode_message(message, G)
print("\nОтправлено:", codeword)

print("\nВ ходе передачи возникла ошибка")
# Вносим однократную ошибку в позицию 2 (можно в любую)
codeword_with_error = add_single_error(codeword, 2)
print("\nПринято:", codeword_with_error)
print("\nДекодирование без исправления:", codeword_with_error[0:4])

# вычисляем синдром
syndrome = np.dot(codeword_with_error, H) % 2
print("\nСиндром:", syndrome)
print("\nВ принятом сообщении есть ошибка")
# Преобразуем синдром в кортеж из целых чисел
syndrome_tuple = tuple(map(int, tuple(syndrome)))
# Исправление ошибки
corrected_codeword = decode_and_correct(codeword_with_error, H, error_table,syndrome_tuple)
print("\nИсправленное слово:", corrected_codeword)

# Проверка корректности исправления
if np.array_equal(codeword, corrected_codeword):
    print("\nОшибка успешно исправлена!")
else:
    print("\nОшибка не была исправлена корректно.")


Исходное сообщение: [1 0 1 1]

Отправлено: [1 0 1 1 0 1 0]

В ходе передачи возникла ошибка

Принято: [1 0 0 1 0 1 0]

Декодирование без исправления: [1 0 0 1]

Синдром: [0 0 1]

В принятом сообщении есть ошибка

Исправленное слово: [1 0 1 1 0 1 0]

Ошибка успешно исправлена!


# 2.5. Сформировать кодовое слово длины n из слова длины k. Внести двукратную ошибку в сформированное слово. Вычислить синдром, исправить ошибку с использованием таблицы синдромов. Убедиться, что полученное слово отличается от отправленного.

In [ ]:
def add_double_error(codeword, error_positions):
    # Добавляем двукратную ошибку
    codeword_with_double_error = codeword.copy()
    for pos in error_positions:
        codeword_with_double_error[pos] ^= 1
    return codeword_with_double_error


message = np.array([1, 0, 0, 1])  # Сообщение длины k=4
print("\nИсходное сообщение:", message)

codeword = encode_message(message, G)
print("\nОтправлено:", codeword)

print("\nВ ходе передачи возникла ошибка")
# Вносим ошибки в позиции 1, 2 (можно в любую)
codeword_with_double_error = add_double_error(codeword, [1, 2])
print("\nПринято:", codeword_with_double_error)
print("\nДекодирование без исправления:", codeword_with_double_error[0:4])
# вычисляем синдром
syndrome = np.dot(codeword_with_double_error, H) % 2
# Синдром
print("\nСиндром:", syndrome)
print("\nВ принятом сообщении есть ошибка")
# Преобразуем синдром в кортеж из целых чисел
syndrome_tuple = tuple(map(int, tuple(syndrome)))
# Исправление ошибки
corrected_codeword = decode_and_correct(codeword_with_error, H, error_table, syndrome_tuple)
print("\nИсправленное слово:", corrected_codeword)
print("\nДекодированное слово:", codeword_with_double_error[0:4])

# Проверка корректности исправления
if np.array_equal(codeword, corrected_codeword):
    print("\nОшибка успешно исправлена!")
else:
    print("\nОшибка не была исправлена корректно.")


Исходное сообщение: [1 0 0 1]

Отправлено: [1 0 0 1 0 0 1]

В ходе передачи возникла ошибка

Принято: [1 1 1 1 0 0 1]

Декодирование без исправления: [1 1 1 1]

Синдром: [1 1 0]

В принятом сообщении есть ошибка

Исправленное слово: [1 0 0 0 0 1 0]

Декодированное слово: [1 1 1 1]

Ошибка не была исправлена корректно.


# 2.6. Сформировать порождающую матрицу линейного кода (n, k, 5).

Подсказка 4:
Чтобы d было равно пяти, необходимо, чтобы в матрице X (без учёта единичной матрицы слева):
а) было не меньше 4 единиц в каждой строке;
б) сумма любых двух строк содержала не менее 3 единиц;
в) сумма любых трёх строк содержала не менее 2 единиц;
г) сумма любых четырёх строк содержала не менее 1 единицы;

In [ ]:
from itertools import combinations

def check_conditions(X):
    # Условие 1: В каждой строке X должно быть не менее 4 единиц
    for row_idx, row in enumerate(X):
        if np.sum(row) < 4:
            raise ValueError(f"Ошибка: в строке {row_idx + 1} меньше 4 единиц. Строка: {row}")

    # Условие 2: Сумма любых двух строк должна содержать не менее 3 единиц
    for (i, j) in combinations(range(X.shape[0]), 2):
        row_sum = np.sum(X[i] + X[j])
        if row_sum < 3:
            raise ValueError(f"Ошибка: сумма строк {i+1} и {j+1} содержит меньше 3 единиц. Сумма: {row_sum}")

    # Условие 3: Сумма любых трёх строк должна содержать не менее 2 единиц
    for (i, j, k) in combinations(range(X.shape[0]), 3):
        row_sum = np.sum(X[i] + X[j] + X[k])
        if row_sum < 2:
            raise ValueError(f"Ошибка: сумма строк {i+1}, {j+1} и {k+1} содержит меньше 2 единиц. Сумма: {row_sum}")

    # Условие 4: Сумма любых четырёх строк должна содержать не менее 1 единицы
    for (i, j, k, l) in combinations(range(X.shape[0]), 4):
        row_sum = np.sum(X[i] + X[j] + X[k] + X[l])
        if row_sum < 1:
            raise ValueError(f"Ошибка: сумма строк {i+1}, {j+1}, {k+1} и {l+1} содержит меньше 1 единицы. Сумма: {row_sum}")

    print("Все условия выполнены!")

def generate_G_matrix(k, n):
    # Проверяем, что n > k
    if n <= k:
        raise ValueError("n должно быть больше k")

    X = np.array([[1, 1, 1, 1, 0, 0],
                  [1, 1, 0, 0, 1, 1],
                  [0, 0, 1, 1, 1, 1],
                  [1, 0, 1, 1, 1, 0]])
    check_conditions(X)
    I_k = np.eye(k, dtype=int)

    G = np.hstack((I_k, X))
    return G

k = 4
n = 10

G_matrix = generate_G_matrix(k, n)
print("\nПроверочная матрица G (10, 4, 5):")
print(G_matrix)

Все условия выполнены!

Проверочная матрица G (10, 4, 5):
[[1 0 0 0 1 1 1 1 0 0]
 [0 1 0 0 1 1 0 0 1 1]
 [0 0 1 0 0 0 1 1 1 1]
 [0 0 0 1 1 0 1 1 1 0]]


# 2.7 Сформировать проверочную матрицу на основе порождающей.

In [ ]:
def generate_H_matrix(k, n):
    # Проверяем, что n > k
    if n <= k:
        raise ValueError("n должно быть больше k")

    X = np.array([[1, 1, 1, 1, 0, 0],
                  [1, 1, 0, 0, 1, 1],
                  [0, 0, 1, 1, 1, 1],
                  [1, 0, 1, 1, 1, 0]])
    check_conditions(X)
    I_n_k = np.eye(n-k, dtype=int)

    H = np.vstack((I_n_k, X))
    return H

k = 4
n = 10

H_matrix = generate_H_matrix(k, n)
print("\nПроверочная матрица G (10, 4, 5):")
print(H_matrix)

Все условия выполнены!

Проверочная матрица G (10, 4, 5):
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [1 1 1 1 0 0]
 [1 1 0 0 1 1]
 [0 0 1 1 1 1]
 [1 0 1 1 1 0]]


# 2.8 Сформировать таблицу синдромов для всех однократных и двукратных ошибок.

In [ ]:
# Задаем матрицу H
H_matrix = np.array([[1, 1, 0, 0, 1, 0, 1],
                     [1, 0, 1, 0, 0, 1, 1],
                     [0, 1, 1, 0, 1, 1, 0],
                     [1, 1, 1, 0, 0, 0, 1]])

# Задаем матрицу G
G_matrix = np.array([[1, 0, 0, 0, 1, 1, 0],
                     [0, 1, 0, 0, 0, 1, 1],
                     [0, 0, 1, 0, 1, 0, 1],
                     [0, 0, 0, 1, 1, 1, 1]])

# Функция для формирования таблицы синдромов
def generate_syndrome_table_2(H_matrix):
    n = H_matrix.shape[1]
    syndrome_table = {}

    # Однократные ошибки
    for i in range(n):
        e = np.zeros(n, dtype=int)
        e[i] = 1
        syndrome = np.dot(H_matrix, e) % 2
        syndrome_table[tuple(map(int, tuple(e)))] = tuple(map(int, tuple(syndrome)))

    # Двукратные ошибки
    for i in range(n):
        for j in range(i+1, n):
            e = np.zeros(n, dtype=int)
            e[i] = 1
            e[j] = 1
            syndrome = np.dot(H_matrix, e) % 2
            syndrome_table[tuple(map(int, tuple(e)))] = tuple(map(int, tuple(syndrome)))

    return syndrome_table


syndrome_table_2 = generate_syndrome_table_2(H_matrix)
print("\nТаблица синдромов для однократных и двукратных ошибок:")
for error, syndrome in syndrome_table_2.items():
    print(f"Ошибка {error}: Синдром {syndrome}")



Таблица синдромов для однократных и двукратных ошибок:
Ошибка (1, 0, 0, 0, 0, 0, 0): Синдром (1, 1, 0, 1)
Ошибка (0, 1, 0, 0, 0, 0, 0): Синдром (1, 0, 1, 1)
Ошибка (0, 0, 1, 0, 0, 0, 0): Синдром (0, 1, 1, 1)
Ошибка (0, 0, 0, 1, 0, 0, 0): Синдром (0, 0, 0, 0)
Ошибка (0, 0, 0, 0, 1, 0, 0): Синдром (1, 0, 1, 0)
Ошибка (0, 0, 0, 0, 0, 1, 0): Синдром (0, 1, 1, 0)
Ошибка (0, 0, 0, 0, 0, 0, 1): Синдром (1, 1, 0, 1)
Ошибка (1, 1, 0, 0, 0, 0, 0): Синдром (0, 1, 1, 0)
Ошибка (1, 0, 1, 0, 0, 0, 0): Синдром (1, 0, 1, 0)
Ошибка (1, 0, 0, 1, 0, 0, 0): Синдром (1, 1, 0, 1)
Ошибка (1, 0, 0, 0, 1, 0, 0): Синдром (0, 1, 1, 1)
Ошибка (1, 0, 0, 0, 0, 1, 0): Синдром (1, 0, 1, 1)
Ошибка (1, 0, 0, 0, 0, 0, 1): Синдром (0, 0, 0, 0)
Ошибка (0, 1, 1, 0, 0, 0, 0): Синдром (1, 1, 0, 0)
Ошибка (0, 1, 0, 1, 0, 0, 0): Синдром (1, 0, 1, 1)
Ошибка (0, 1, 0, 0, 1, 0, 0): Синдром (0, 0, 0, 1)
Ошибка (0, 1, 0, 0, 0, 1, 0): Синдром (1, 1, 0, 1)
Ошибка (0, 1, 0, 0, 0, 0, 1): Синдром (0, 1, 1, 0)
Ошибка (0, 0, 1, 1, 0, 0, 

# 2.9. Сформировать кодовое слово длины n из слова длины k. Внести однократную ошибку в сформированное слово. Вычислить синдром, исправить ошибку с использованием таблицы синдромов. Убедиться в правильности полученного слова.

In [ ]:


# Генерация порождающей матрицы (для кода Хэмминга (7,4))
def generate_G():
    # Порождающая матрица G для (7,4) кода
    I = np.eye(4, dtype=int)  # Единичная матрица 4x4
    X = np.array([[1, 1, 0], [1, 0, 1], [0, 1, 1], [1, 1, 1]], dtype=int)  # Матрица дополнений
    G = np.concatenate((I, X), axis=1)  # G = [I | X]
    return G

# Генерация проверочной матрицы H
def generate_H():
    # Проверочная матрица H для (7,4) кода
    X = np.array([[1, 1, 0], [1, 0, 1], [0, 1, 1], [1, 1, 1]], dtype=int)
    I = np.eye(3, dtype=int)  # Единичная матрица 3x3
    H = np.concatenate((X.T, I), axis=1)  # H = [X^T | I]
    return H

# Формирование кодового слова
def encode(data_bits, G):
    # Кодирование сообщения (data_bits) с помощью порождающей матрицы G
    data_bits = np.array(data_bits, dtype=int)
    codeword = np.dot(data_bits, G) % 2  # Умножение по модулю 2
    return codeword

# Внесение ошибки в кодовое слово
def introduce_error(codeword):
    # Случайное внесение однократной ошибки
    error_position = np.random.randint(0, len(codeword))
    codeword[error_position] ^= 1  # Инвертируем бит
    return codeword, error_position

# Вычисление синдрома
def calculate_syndrome(codeword, H):
    # Синдром для проверки ошибок
    syndrome = np.dot(H, codeword) % 2
    return syndrome

# Исправление ошибки на основе синдрома
def correct_error(codeword, syndrome, H):
    # Находим позицию ошибки по синдрому
    for i in range(len(H.T)):
        if np.array_equal(H[:, i], syndrome):
            codeword[i] ^= 1  # Исправляем ошибку
            break
    return codeword

# Основная программа
def main():
    # Шаг 1: Генерация порождающей и проверочной матриц
    G = generate_G()
    H = generate_H()

    # Шаг 2: Вводим данные длины 4 (пример)
    data_bits = [1, 0, 0, 1]
    print("Исходные данные:", data_bits)

    # Шаг 3: Формирование кодового слова
    codeword = encode(data_bits, G)
    print("Сгенерированное кодовое слово:", codeword)

    # Шаг 4: Внесение однократной ошибки
    codeword_with_error, error_position = introduce_error(codeword.copy())
    print(f"Кодовое слово с ошибкой (ошибка в позиции {error_position}):", codeword_with_error)

    # Шаг 5: Вычисление синдрома
    syndrome = calculate_syndrome(codeword_with_error, H)
    print("Синдром ошибки:", syndrome)

    # Шаг 6: Исправление ошибки
    corrected_codeword = correct_error(codeword_with_error.copy(), syndrome, H)
    print("Исправленное кодовое слово:", corrected_codeword)

    # Шаг 7: Проверка правильности
    if np.array_equal(corrected_codeword, codeword):
        print("Ошибка успешно исправлена!")
    else:
        print("Ошибка исправлена неверно.")

if __name__ == "__main__":
    main()


Исходные данные: [1, 0, 0, 1]
Сгенерированное кодовое слово: [1 0 0 1 0 0 1]
Кодовое слово с ошибкой (ошибка в позиции 5): [1 0 0 1 0 1 1]
Синдром ошибки: [0 1 0]
Исправленное кодовое слово: [1 0 0 1 0 0 1]
Ошибка успешно исправлена!


*# 2.10. Сформировать кодовое слово длины n из слова длины k. Внести двукратную ошибку в сформированное слово. Вычислить синдром, исправить ошибку с использованием таблицы синдромов. Убедиться в правильности полученного слова.*

In [ ]:


# Функция для вычисления синдрома
def calculate_syndrome(code_word_with_error, H_matrix):
    # Вычисление синдрома
    syndrome = np.dot(code_word_with_error, H_matrix.T) % 2
    return syndrome

# Слово длины k = 6
word = np.array([1, 0, 1, 0, 1, 0])
print("word = ", word)

# Порождающая матрица G (6, 11)


# Создание кодового слова длины n = 11, добавление контрольных символов
code_word = np.dot(word, G) % 2
print("code_word = ", code_word)

# Внесение ошибок в кодовое слово (позиции 3 и 5)
error_positions = [3, 5]
code_word_with_error = np.copy(code_word)
for i in error_positions:
    code_word_with_error[i] = (code_word_with_error[i] + 1) % 2
print("code_word_with_error = ", code_word_with_error)

# Проверочная матрица H (11, 5) для вычисления синдрома

# Вызов функции для вычисления синдрома
syndrome = calculate_syndrome(code_word_with_error, H)
print("syndrome = ", syndrome)

# Таблица синдромов для двукратных ошибок (пример)
tableForTwoError = {
    (1, 0, 1, 0, 1): (0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1),  # Добавьте корректные синдромы
    # Добавьте больше двукратных ошибок
}

# Поиск возможных позиций ошибок
possibleErrorPosition = []
for error, s in tableForTwoError.items():
    if tuple(syndrome) == s:
        mass = list(error)
        pos = []
        for i in range(len(mass)):
            if mass[i] == 1:
                pos.append(i)
        possibleErrorPosition.append(pos)

# Исправление ошибки
flag = True
corrected_codeword = None  # Объявляем переменную для хранения исправленного кодового слова

# Проход по найденным возможным позициям ошибок
for error_pos in possibleErrorPosition:
    copy_word = np.copy(code_word_with_error)  # Создаем копию для тестирования исправления
    copy_word[error_pos[0]] = (copy_word[error_pos[0]] + 1) % 2  # Исправляем первую ошибку
    copy_word[error_pos[1]] = (copy_word[error_pos[1]] + 1) % 2  # Исправляем вторую ошибку

    # Проверка правильности полученного кодового слова
    flag_error_copy_word = False
    for i in range(len(copy_word)):
        if copy_word[i] != code_word[i]:
            flag_error_copy_word = True
            break

    if not flag_error_copy_word:  # Если кодовое слово совпадает с оригиналом, ошибка исправлена
        corrected_codeword = copy_word  # Сохраняем исправленное кодовое слово
        flag = False
        break

if flag:
    print("Ошибка не была обнаружена и/или не была успешно исправлена")
    print('code_word = ', code_word)
else:
    print("Ошибка успешно обнаружена и исправлена")
    print('code_word = ', code_word)
    print('code_word_without_error = ', corrected_codeword, '\n')


word =  [1 0 1 0 1 0]
code_word =  [1 0 1 0 1 0 0 0 1 0 0]
code_word_with_error =  [1 0 1 1 1 1 0 0 1 0 0]
syndrome =  [0 1 0 1 0]
Ошибка не была обнаружена и/или не была успешно исправлена
code_word =  [1 0 1 0 1 0 0 0 1 0 0]


# 2.11. Сформировать кодовое слово длины n из слова длины k. Внести трёхкратную ошибку в сформированное слово. Вычислить синдром, исправить ошибку с использованием таблицы синдромов. Убедиться, что полученное слово отличается от отправленного.

In [ ]:

from itertools import combinations

# Функция для вычисления синдрома
def calculate_syndrome(code_word_with_error, H_matrix):

    syndrome = np.dot(code_word_with_error, H_matrix.T) % 2
    return syndrome

# Функция для генерации таблицы синдромов для трёхкратных ошибок
def generate_syndrome_table(H_matrix):


    table = {}
    n = H_matrix.shape[1]  # Длина кодового слова
    # Генерация всех комбинаций 3-х ошибок (трёхкратные ошибки)
    for error_pos in combinations(range(n), 3):
        error_vector = np.zeros(n, dtype=int)
        for pos in error_pos:
            error_vector[pos] = 1
        syndrome = tuple(np.dot(error_vector, H_matrix.T) % 2)  # Вычисление синдрома для трёхкратной ошибки
        table[syndrome] = error_vector  # Сохраняем синдром и соответствующую ошибку в таблице
    return table

# Слово длины k = 6
word = np.array([1, 0, 1, 0, 1, 0])
print("word = ", word)

# Порождающая матрица G (6, 11)


# Создание кодового слова длины n = 11, добавление контрольных символов
code_word = np.dot(word, G) % 2
print("code_word = ", code_word)

# Внесение трёхкратной ошибки (позиции 1, 4, 6)
error_positions = [1, 4, 6]
code_word_with_error = np.copy(code_word)
for i in error_positions:
    code_word_with_error[i] = (code_word_with_error[i] + 1) % 2
print("code_word_with_error = ", code_word_with_error)

# Проверочная матрица H (11, 5) для вычисления синдрома


# Вызов функции для вычисления синдрома
syndrome = calculate_syndrome(code_word_with_error, H)
print("syndrome = ", syndrome)

# Генерация таблицы синдромов для трёхкратных ошибок
tableForThreeError = generate_syndrome_table(H)
print("Таблица синдромов для трёхкратных ошибок сгенерирована")

# Поиск возможных позиций ошибок
possibleErrorPosition = []
if tuple(syndrome) in tableForThreeError:
    error_vector = tableForThreeError[tuple(syndrome)]
    possibleErrorPosition = [i for i, bit in enumerate(error_vector) if bit == 1]

# Исправление ошибки
flag = True
corrected_codeword = None  # Объявляем переменную для хранения исправленного кодового слова

# Проход по найденным возможным позициям ошибок
if possibleErrorPosition:  # Проверка, что найдены возможные ошибки
    copy_word = np.copy(code_word_with_error)  # Создаем копию для тестирования исправления
    for pos in possibleErrorPosition:
        copy_word[pos] = (copy_word[pos] + 1) % 2  # Исправляем ошибку

    # Проверка правильности полученного кодового слова
    if np.array_equal(copy_word, code_word):  # Если кодовое слово совпадает с оригиналом, ошибка исправлена
        corrected_codeword = copy_word  # Сохраняем исправленное кодовое слово
        flag = False

if flag or corrected_codeword is None:
    print("Ошибка не была обнаружена и/или не была успешно исправлена")
    print('code_word = ', code_word)
    print('code_word_with_error = ', code_word_with_error)
else:
    print("Ошибка успешно обнаружена и исправлена")
    print('code_word = ', code_word)
    print('code_word_without_error = ', corrected_codeword, '\n')

# Убедиться, что полученное слово отличается от отправленного
if not np.array_equal(code_word_with_error, code_word):
    print("Полученное кодовое слово отличается от отправленного (с ошибками)")
else:
    print("Полученное кодовое слово не отличается от отправленного")


word =  [1 0 1 0 1 0]
code_word =  [1 0 1 0 1 0 0 0 1 0 0]
code_word_with_error =  [1 1 1 0 0 0 1 0 1 0 0]
syndrome =  [0 0 1 0 1]
Таблица синдромов для трёхкратных ошибок сгенерирована
Ошибка не была обнаружена и/или не была успешно исправлена
code_word =  [1 0 1 0 1 0 0 0 1 0 0]
code_word_with_error =  [1 1 1 0 0 0 1 0 1 0 0]
Полученное кодовое слово отличается от отправленного (с ошибками)
